vim.cmd [[colorscheme dracula]]
-- require('solarized').setup {
--   enables = {
--       editor = true,
--       syntax = true,
--
--       -- PLUGINS
--       bufferline = true,
--       cmp = true, -- disabled
--       diagnostic = true,
--       indentblankline = true,
--       lsp = true,
--       lspsaga = false, -- disabled
--       navic = true,
--       semantic = true,
--       telescope = true,
--       neotree = true, -- disabled
--       treesitter = true,
--       theme = "neo";
--     },
--     highlights = {
--         -- your implementation of nvim-tree
--         -- your implementation of cmp
--         -- your implementation of lspsaga
--
--     }
-- }
